### ISSUE TITLE
typescript `enum` is a reserved word

### ISSUE THREAD

**Issue by PlayMa256** [fkling/astexplorer#523] opened 2020-07-27 15:21 UTC
**Describe the bug**
trying to use `typescript` with `@typescript-eslint/parser` and I'm getting this error message.

**To Reproduce**
https://astexplorer.net/#/gist/1d19afcd40553c9a8c2d1f009d8ec283/22ec42caaac3d8f5b97f3593688f4faca7480f86

**Expected behavior**
Parse correctly

**Comment by fkling** [comment] 2020-07-28 21:41
Unfortunately this currently works as "intended". The selected parser is in no way connected to the transformer. I.e. eslint is running with the default parser. Making these two parts "connected" probably requires a very different approach. The transformer will probably have to expose its own parse method somehow.

Basically a duplicate of https://github.com/fkling/astexplorer/issues/462

**Closed by fkling** 2020-07-28 21:41 UTC
