### ISSUE TITLE
Chrome DevTools fails to set breakpoints

### ISSUE THREAD

**Issue by jasonLaster** [fkling/astexplorer#40] opened 2015-10-20 20:59 UTC
when i try to set a breakpoint in Devtools, it's either not set of jumps to a bad place in the source map. Is this something you're seeing as well?

![gif](http://g.recordit.co/BsUFaLjAXY.gif)

P.S. Other than that, I really like the breakdown of the app. Really clean

**Comment by fkling** [comment] 2015-10-20 21:59
I would think this is a general problem with source maps (I have noticed that in other cases), but how did you even got source maps to work with astexplorer?

**Comment by hzoo** [comment] 2015-10-20 21:59
I've had that issue in general with other sites too!

**Comment by jasonLaster** [comment] 2015-10-20 23:42
I added `--debug -d` and `-mn -mnf` to watchify. Would be great to get this working 100%.

```
    "watch": "watchify -p [partition-bundle --map partition.json --output ./ --main ./src/app] -g [uglifyify -c drop_debugger=false -nm -nmf ] -o /dev/null -v --debug -d ",
````

How do you generally debug the app? do you just debug the bundle?

**Comment by fkling** [comment] 2015-10-21 00:49
Ah I see. I added `--debug` as well, but that didn't work for me at first for some reason. Now it seems to work, but I also can't set breakpoints from the debugger.

Maybe the issue is that the source maps are not correctly merged / updated between browserify, babel and uglify. But I also don't know what to do to make it work.

> How do you generally debug the app? do you just debug the bundle?

Yeah, I usually just add a `debugger` or `console.log` statement, or break on exception and figure it out from there.

**Comment by jasonLaster** [comment] 2015-10-21 01:09
Hmm, let's try it w/o the partition.

**Comment by fkling** [comment] 2015-11-21 02:08
I switched to webpack in 89db32fcfb1bdab3dfd07b7317c7e40faa4c66c2, but the source maps are still messed up. Maybe I still have to configure something differently...

**Comment by RReverser** [comment] 2015-11-21 23:53
This is actually totally normal thing on any minified source. That is, some minification can remove code you see or inline it as expression, in which case it will be still displayed through source maps, but location won't be linked to any statement in real (minified code) and thus debugger won't be able to stop there.

**Comment by fkling** [comment] 2016-06-12 22:53
Closing this since I don't think I can do anything about this.

**Closed by fkling** 2016-06-12 22:53 UTC
