### ISSUE TITLE
License file 

### ISSUE THREAD

**Issue by mistic** [fkling/astexplorer#349] opened 2018-10-20 23:20 UTC
@fkling thanks for your work into this helpful tool! I saw some parts of this project are licensed under `MIT` https://github.com/fkling/astexplorer/blob/5794b4d1afdfb5c249c2b972f98ff6e884765b33/website/package.json#L11

Do you think it's possible to add a license file to the root of the repository?

**Comment by KenanY** [comment] 2018-12-06 14:45
Duplicate of https://github.com/fkling/astexplorer/issues/215?

**Comment by fkling** [comment] 2022-05-06 18:05
License was added in 8f2af0237bbecfe24718116bb58f12d5898ee867 .

**Closed by fkling** 2022-05-06 18:05 UTC
