### ISSUE TITLE
astexplorer.net is crashing

### ISSUE THREAD

**Issue by seanmcintyre** [fkling/astexplorer#446] opened 2019-09-27 14:28 UTC
**Screenshots**
<img width="206" alt="Screen Shot 2019-09-27 at 10 27 36 AM" src="https://user-images.githubusercontent.com/319302/65777172-83984980-e111-11e9-9638-64d392dcbf85.png">
<img width="618" alt="Screen Shot 2019-09-27 at 10 25 48 AM" src="https://user-images.githubusercontent.com/319302/65777174-83984980-e111-11e9-8f7b-be01e7a3ef95.png">

**Browser (please complete the following information):**
 - OS: macOS 10.14.4
 - chrome, safari, firefox

**astexplorer settings:**
- Selected parser: typescript
- Selected transformer: jscodeshift

**Comment by RReverser** [comment] 2019-09-27 14:31
It does say it's possible out-of-memory issue, so maybe your input is too large?

**Comment by seanmcintyre** [comment] 2019-09-27 17:07
Definitely not. It crashes when my input is a single import and `function(`

**Comment by fkling** [comment] 2019-10-31 22:34
I can confirm that there something strange going on here. I think the error is not related though (that probably comes from recast trying to parse the `import` statement).

The issue doesn't seem to exist if no transformer is selected. I will have to dig deeper but this is quite mysterious atm.

**Comment by andrewbranch** [comment] 2019-11-07 22:43
Happens for me with TypeScript and no transformers. It’s hard to tell what the infinite loop is because of minified code and generator runtime, but `hasChildrenInRange` is usually in the stack, same as @seanmcintyre’s screenshot.

**Comment by fkling** [comment] 2019-11-07 23:06
I believe TS AST contains circular references. While they *should* be ignored, maybe we are missing some keys in https://github.com/fkling/astexplorer/blob/8e117e3881f2cd06e4da5ccc2410c8939bf9ff2e/website/src/parsers/js/typescript.js#L97-L99

**Comment by andrewbranch** [comment] 2019-11-07 23:11
I can’t think of anything other than `parent` that would let you traverse any direction other than down. Certainly nothing new in 3.6 that I’m aware of... it seems like this is happening after the upgrade to the 3.6 parser; maybe we should roll back or try 3.7 now that the stable release is out? I would love to help out but definitely can’t this week; maybe sometime next week if you haven’t gotten to it.

**Comment by fkling** [comment] 2019-11-08 13:08
Alright, I figured out what the problem is @andrewbranch . When there is a syntax error, `parseDiagnostics` is not empty and contains a circular reference with property name `file`.

It's easy to blacklist this, but I'm also wondering whether we should just print the error message if an error is detected, instead of printing the AST.

What do you think?

**Comment by fkling** [comment] 2019-11-08 14:38
33eb65b09881dfbd56f59801172ae01faa875d0f should fix the crash. I will close the issue once it's deployed.

**Comment by andrewbranch** [comment] 2019-11-08 15:12
> I'm also wondering whether we should just print the error message if an error is detected, instead of printing the AST.

Why not both? Knowing a syntax error exists is great, but it’s also really interesting to see how the parser recovers in an error scenario. For example, when the parser encounters a lone JSX element, it synthesizes a comma expression around it in order to recover, and issues a syntax error. In my opinion it’s really useful to be able to see that. (Plus, if you’re in the middle of typing some syntax, most keystrokes are a syntax error until you’re done typing, and it would be annoying if the AST was flashing in and out while typing.)

**Comment by IllusionMH** [comment] 2019-11-08 15:38
Would prefer both. There were few occasions where AST explorer helped to identify problems with how TS parses files and AST was most helpful part here, because I already knew that there was an error from VS Code editor.

**Comment by fkling** [comment] 2019-11-08 23:43
Then we'll just leave it as it is for now :wink:

**Comment by fkling** [comment] 2019-11-09 18:27
OK, this is finally live at https://astexplorer.net (+ updated TS parser), after I sorted out the build issues.

**Closed** 2019-11-09 18:27 UTC
Labels: bug, deployed to production, deployed to staging
