### ISSUE TITLE
windows platform build error

### ISSUE THREAD

**Issue by deno-source** [fkling/astexplorer#638] opened 2022-03-10 09:57 UTC
Error message:
```js
ERROR in ./node_modules/acorn-loose/dist/acorn-loose.mjs 1420:30-38
Can't import the named export 'tokTypes' from non EcmaScript module (only default export is available)
 @ ./src/parsers/js/acorn.js
 @ ./src/parsers sync ^\.\/(?!utils|transpilers)[^/]+\/(transformers\/([^/]+)\/)?(codeExample\.txt|[^/]+?\.js)$
 @ ./src/parsers/index.js
 @ ./src/storage/parse.js
 @ ./src/app.js
```

**Comment by fkling** [comment] 2022-05-06 18:20
Duplicate of #585, but thank your for the stack trace.

**Closed by fkling** 2022-05-06 18:20 UTC
